import {Food} from "./model/food";

export const data: Food[] = [
  {
    id:1,
    name:'Chocolate Laptop',
    type:'Food Group 1',
    allergies:['Nuts','Lactose'],
    taste:'Great',
    season:"All",
    desc:'Taste like candy and its chocolate!',
    calories:200,
    weight:1,
    in_stock:100,
  },
  {
    id:1,
    name:'Chocolate Laptop',
    type:'Food Group 1',
    allergies:['Nuts','Lactose'],
    taste:'Great',
    season:"All",
    desc:'Taste like candy and its chocolate!',
    calories:200,
    weight:1,
    in_stock:100,
  },
  {
    id:1,
    name:'Chocolate Laptop',
    type:'Food Group 1',
    allergies:['Nuts','Lactose'],
    taste:'Great',
    season:"All",
    desc:'Taste like candy and its chocolate!',
    calories:200,
    weight:1,
    in_stock:100,
  },
  {
    id:1,
    name:'Chocolate Laptop',
    type:'Food Group 1',
    allergies:['Nuts','Lactose'],
    taste:'Great',
    season:"All",
    desc:'Taste like candy and its chocolate!',
    calories:200,
    weight:1,
    in_stock:100,
  },
  {
    id:1,
    name:'Chocolate Laptop',
    type:'Food Group 1',
    allergies:['Nuts','Lactose'],
    taste:'Great',
    season:"All",
    desc:'Taste like candy and its chocolate!',
    calories:200,
    weight:1,
    in_stock:100,
  },
  {
    id:1,
    name:'Chocolate Laptop',
    type:'Food Group 1',
    allergies:['Nuts','Lactose'],
    taste:'Great',
    season:"All",
    desc:'Taste like candy and its chocolate!',
    calories:200,
    weight:1,
    in_stock:100,
  },
  {
    id:1,
    name:'Chocolate Laptop',
    type:'Food Group 1',
    allergies:['Nuts','Lactose'],
    taste:'Great',
    season:"All",
    desc:'Taste like candy and its chocolate!',
    calories:200,
    weight:1,
    in_stock:100,
  }

]
